### ISSUE TITLE
haarcascade_frontalface_default.xml i need this file 

### ISSUE THREAD

**Issue by rakeshrohan-123** [vschs007/realtime-face-detection-using-python-and-opencv#3]

**Comment by vschs007** [comment]
Sure, I will share it with you

**Comment by vschs007** [comment]
https://github.com/vschs007/flask-realtime-face-detection-opencv-python/blob/master/haarcascade_frontalface_default.xml
here is the file

**Comment by rakeshrohan-123** [comment]
i am getting  this Sorry about that, but we can’t show files that are this
big right now i am not able to view or download file.

**Comment by rakeshrohan-123** [comment]
please see the screen shot  Sorry about that, but we can’t show files that
are this big right now .please get me link to download file

**Comment by vschs007** [comment]
yes sure, I will attach a link to download the file
